[build]
  base = ""
  publish = "build/"
  command = "npm install; npm run-script build"
[[redirects]]
  from = "https://hacs.netlify.com"
  to = "https://hacs.xyz"
  status = 301
  force = true